Repository arm-developer-tools/windowsperf, pull requests merged in 2024-11, with the labels that each got.

#58 fix: user_request::check_events comparison logic
  wperf/user_request.cpp
Labels: bug

#59 [wperf] Refactorying before adding new min_latency filter
  wperf-scripts/tests/wperf_cli_cpython_dep_record_spe_test.py
  wperf-test/wperf-test-parsers.cpp
  wperf-test/wperf-test-utils.cpp
  wperf/README.md
  wperf/parsers.cpp
  wperf/parsers.h
  wperf/pmu_device.cpp
  wperf/pmu_device.h
  wperf/spe_device.h
  wperf/user_request.cpp
  wperf/user_request.h
  wperf/utils.h
Labels: enhancement

#60 [wperf] Add (in verbose mode / -v) prints for PCs and symbols discovered
  wperf/main.cpp
Labels: enhancement

#61 [wperf-driver,wperf] [SPE] Add minimum Latency filter `min_latency=<n>` to arm_spe_0//
  wperf-common/iorequest.h
  wperf-driver/spe.c
  wperf-driver/spe.h
  wperf-scripts/tests/wperf_cli_cpython_dep_record_spe_test.py
  wperf/README.md
  wperf/pmu_device.cpp
  wperf/spe_device.cpp
  wperf/spe_device.h
Labels: enhancement

#64 Add SPE filter name getter from alias or name
  wperf-test/wperf-test-spe_device.cpp
  wperf/pmu_device.cpp
  wperf/spe_device.cpp
  wperf/spe_device.h
Labels: enhancement

#65 Add symbol name for `pcs` list of PCs in sampling
  wperf-scripts/tests/schemas/wperf.sample.schema
  wperf-scripts/tests/wperf_cli_cpython_dep_record_spe_test.py
  wperf/main.cpp
  wperf/output.h
Labels: enhancement

#69 [wperf] Update usage docs for wperf CLI
  wperf/README.md
  wperf/user_request.cpp
Labels: documentation

#67 [wperf-scripts] Add flake8 and mypy config to wperf-scripts/tests
  wperf-scripts/tests/.flake8
  wperf-scripts/tests/Makefile
  wperf-scripts/tests/mypy.ini
Labels: CI / testing

#74 Adding arg parser files
  wperf-test/arg-parser-arg-tests.cpp
  wperf-test/arg-parser-arg-utils-tests.cpp
  wperf-test/arg-parser-tests.cpp
  wperf-test/wperf-test.vcxproj
  wperf-test/wperf-test.vcxproj.filters
  wperf/arg-parser-arg.cpp
  wperf/arg-parser-arg.h
  wperf/arg-parser.cpp
  wperf/arg-parser.h
  wperf/wperf.vcxproj
  wperf/wperf.vcxproj.Filters
Labels: enhancement

#75 [wperf,wperf-test] Align arg_parser code tests with
  wperf-test/wperf-test-arg_parser.cpp
  wperf-test/wperf-test-arg_parser_arg-utils.cpp
  wperf-test/wperf-test-arg_parser_arg.cpp
  wperf-test/wperf-test.vcxproj
  wperf-test/wperf-test.vcxproj.filters
  wperf/arg_parser.cpp
  wperf/arg_parser.h
  wperf/arg_parser_arg.cpp
  wperf/arg_parser_arg.h
  wperf/wperf.vcxproj
  wperf/wperf.vcxproj.Filters
Labels: CI / testing

#77 [wperf-test] Add more comprehensive test to check parser
  wperf-test/wperf-test-arg_parser.cpp
Labels: CI / testing

#78 [docs]: Typo in USAGE.md
  USAGE.md
Labels: bug

#79 [wperf]: fix string escaping
  wperf/arg_parser.h
Labels: bug
